language: generic
os: linux
dist: trusty
compiler: g++
sudo: required
services: docker

git:
  quiet: true
  depth: 1

before_script:
  - python scripts/outputstreams_set_blocking.py
  - git clone https://github.com/mypaint/mypaint.git
  - git clone https://github.com/mypaint/libmypaint.git
  - git clone https://github.com/mypaint/mypaint-brushes.git
  - 'if [ -e travis.cancel ]; then
        exit 0;
    fi'
  - travis_wait 20 # 20 minutes should be plenty to pull the docker image
    sudo docker pull mypaint/appimage-base:1.0.0
  - sudo docker run -t -v $(pwd):/sources -e "GIT_BRANCH=master"
    mypaint/appimage-base:1.0.0 bash /sources/scripts/mkappimage.sh

after_success:
    - cd $TRAVIS_BUILD_DIR
    - ls -lh out/* # Assuming you have some files in out/ that you would like to upload
    - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
    - bash  ./upload_rotate.sh "continuous" out/* >& /dev/null

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

