language: generic
os: linux
dist: xenial
compiler: g++
sudo: required
services: docker

git:
  quiet: true
  depth: 1

addons:
  apt:
    packages:
      python3
      python3-pip

install:
  - pip3 install requests

before_script:
  - python --version
  - python3 --version
  - git clone https://github.com/mypaint/mypaint.git
  - git clone https://github.com/mypaint/libmypaint.git
  - git clone https://github.com/mypaint/mypaint-brushes.git
  - # 20 minutes should be plenty to pull the docker image
  - travis_wait 20
    sudo docker pull mypaint/appimage-base:1.0.0

script:
  - sudo docker run -t -v $(pwd):/sources mypaint/appimage-base:1.0.0
    bash /sources/scripts/mkappimage.sh

after_success:
    - cd $TRAVIS_BUILD_DIR
    - ls -lh out/*
    - bash ./scripts/upload.sh out/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:continuous-rotating)$/

